name: Docker Build Single

on: [push]

env:
  CACHE_IMAGE: sz3jdii/pfswchoz2
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Log in to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup new Builder
        run: |
          docker buildx create --name mybuilder
      - name: Select new Builder
        run: |
          docker buildx use mybuilder
      - name: Bootstrap new Builder
        run: |
          docker buildx inspect --bootstrap
      - name: Build from dockerfile
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
      - name: Push to docker hub
        run: docker push $CACHE_IMAGE:latest